#列表
list=['liliy','liuhai','lili','jia']
print(list)
print(list[2:3])
print(list[0])
print(list*2)
list[0]='lili1'
print(list[0])
#字符串
s='abcdefghigklmn'
print(s[2:])
print(s[2:4])
print(s[:5])
print(s[:5:2])
#元组,
y=('list','tuple','lili','liuhai','lili')
print(y[1])
print(y)
#error,不允许更新
#y[1]='tuple1'
print(y[1])
#字典，就相当于json
zidian={"name":"liudan","id":101,"sex":"女"}
print(zidian)
#所有的key
print(zidian.keys())
#所有的value
print(zidian.values())


